### ISSUE TITLE
Page not found for ICA link

### ISSUE THREAD

**Issue by skanwal** [umccr/ica-ica-lazy#22]
The link to ICA binary needs updating here https://github.com/umccr/ica-ica-lazy/wiki/Getting_Started#downloading-the-ica-binary

**Comment by alexiswl** [comment]
Ah well found, new page is here - https://illumina.gitbook.io/ica-v1/command-line-interface/cli-releasehistory will update this in the next release

**Comment by alexiswl** [comment]
Resolved by #24
