### ISSUE TITLE
Feature request: gds-summarise, like gds-usage but prints out a summary instead.  

### ISSUE THREAD

**Issue by alexiswl** [umccr/ica-ica-lazy#33]
Some details would be:

* Number of files in directory
* Number of folders in directory
* Size of directory
* Optional data-graph to show number of files produced over time in folder

**Comment by alexiswl** [comment]
@ohofmann also looking for some suggestions here

**Comment by ohofmann** [comment]
I think this would be terrific already. My normal usage pattern on the command line also frequently includes limiting to certain filetypes (by suffix) - basically what's the size of the BAMs in a folder vs everything else - but that's something we can already get out of file listings, I think...
