### ISSUE TITLE
ica-add-access-token fails

### ISSUE THREAD

**Issue by brainstorm** [umccr/ica-ica-lazy#4]
Summary of our private conversations over Slack:

```
% ica-add-access-token --project-name production --scope admin
Creating a personal access token
Getting project id from project name
Creating project token
Error: Could not create a project access token

(adding -x to the shell script...)

% ica-add-access-token --project-name production --scope admin
++ token_obj=
++ jq --raw-output .access_token
+ project_access_token=
+ [[ -z '' ]]
+ echo_stderr 'Error: Could not create a project access token'
+ : '
  Print output to stderr
  '
+ echo 'Error: Could not create a project access token'
Error: Could not create a project access token
+ exit 1
```

```
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Tue, 11 Jan 2022 02:57:36 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
* The requested URL returned error: 401
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (22) The requested URL returned error: 401
```

1. I removed the API key altogether and created a new one.
2. Made sure no `ICA_*` old variables were polluting the env.
3. Made sure regular `ica projects enter production` works.
4. `.ica-ica-lazy` directory `tokens` did not exist, did a `mkdir` for that.
5. Examined the PAT, there seems to be some discrepancies according to @alexiswl one.

**Comment by alexiswl** [comment]
Hi @brainstorm looked through your API, and it seems that it does not have the permissions for GMS scopes.  I have removed these from all permission levels when generating project-based tokens

**Comment by alexiswl** [comment]
Resolved with removal of unnecessary scopes
